### PR TITLE
Update path to pickle file in Cavity flow exercise

### PR DESCRIPTION
**Pull request by nicoguaro**

### CODE REVIEW

**Comment by gforsyth** [comment]
Hey @nicoguaro -- thanks for putting this in!  I appreciate it!

Could you remove `notebooks/05.1.Cavity_Flow.ipynb` and the updated pickle file from the PR?  Thanks!

**Comment by nicoguaro** [comment]
I think that is easier to create a new PR. Also, isn't a good idea to add pickle files to .gitignore?

**Comment by gforsyth** [comment]
Hey @nicoguaro -- a new PR works for me!  And yes, it's a good idea to add pickle files to the `gitignore`.

**Comment by nicoguaro** [comment]
Done, check #9

**Comment by gforsyth** [comment]
Closing in favor of #9

**Pull request closed without merging**
